language: node_js

env:
  global:
    - NPM_CONFIG_LOGLEVEL=warn
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.2
    - ANDROID_SDK_ROOT=/usr/local/android-sdk/
    - secure: ZzSXv0mXeBuJ3Lb+zIHXn04vTxve1C9LYCdVZmqibPCbc0k5DA3up/sSuMsJzUqoS4FxOCm1wOq/oXvEgBEJgxjCkevH7Qo9V7AtCHgs6gF2yaeBFdm1jjf7sB2BxO9F3EcpPSgWXHNNRX6SFxw0a3qMLvE5kDZIzDwIaOtR/j9NweiIXkua2gZkuOKqc18HulTZ5zlK/XBW4TrOwxJyDOYYHTdzhYXVVdK5lFof8pd6MUpk+s5eRxtBPtDq4GO4MPtj1Z5dYmhEUALEepJAjYRWqhzlsVwWwqAChJDEhUYoyAXVS9Mf+LZrD5LDzWYcmCrlsebPczEcEKoN+CMRmNW8w6/l+xPoPYac7nubtQCqZA32LkdGQ/7oG6w2ttsKnotREp/1JAGpi59uEOeJ3EjysGOH5Y+pphNgLjZg2UICoT3rYwqglKSARdLMIBfgzVF3aHVnRgUam8i830DSHTrc5ShxpL6O0mwZa6Bemf9jwsXC5Dpo0XaIbA4zOV+Y4Gq98YBN9U3Y50dyPbbsc5VTRlCJZrC7+vIgNgy8P4vYsITip3Nj9pAmKNFV1t3ChtkxI6Q7CM70CVdJALeireeok0kz+HKbuOy0t0Efz90lPj+WsleZEJBve7AFYPzR1h6Czs072X4sQlPXedcCHRhD48WgbBX0IfzTiAYCuG0=

# cache:
#   directories:
#     - node_modules

# _shared_job: &shared_job
#   script: echo "shared script config"

jobs:
  include:

####### JS BUILD ########
    - language: node_js
      install:
        - npm install
        - npm run link

      script:
        - set -e
        - ./scripts/check-pristine-state package-lock.json ios/native.xcodeproj/project.pbxproj ios/native/Info.plist
        - npm run danger
        - TZ=Europe/London npm test

      after_script:
        - 'if [ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_API_KEY" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/Skyscanner%2Fbackpack-docs/requests; fi'

####### ANDROID BUILD ########
    - language: android
      sudo: required
      
      before_install:
        # Decode gcloud service key
        - openssl aes-256-cbc -K $encrypted_b11d52d95771_key -iv $encrypted_b11d52d95771_iv -in gcloud-service-key.json.enc -out $HOME/gcloud-service-key.json -d
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export $CLOUDSDK_CORE_DISABLE_PROMPTS; curl https://sdk.cloud.google.com | bash; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc # Add gcloud to $PATH
        - gcloud version
        - gcloud config set project $GCLOUD_PROJECT_ID
        - gcloud auth activate-service-account --key-file $HOME/gcloud-service-key.json
        - chmod +x android/gradlew
        - nvm install
        - nvm use
        - yes | sdkmanager "platforms;android-"$ANDROID_API_LEVEL

      install:
        - npm install

      script: 
        - ./android/gradlew -p android :app:assembleDebug :backpack-react-native:assembleAndroidTest
        - ./scripts/android/ci-tests.sh

      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_LEVEL

      before_cache:
        # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          # Gradle dependencies
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

          # Android build cache (see http://tools.android.com/tech-docs/build-cache)
          - $HOME/.android/build-cache

          # Node modules
          - node_modules

          # Maven cache
          - $HOME/.m2

          # Gcloud
          - $HOME/google-cloud-sdk

branches:
  only:
    - master
    - /^greenkeeper/.*$/

notifications:
  slack:
    rooms:
      - secure: 0kcw0/iGqd4JPjvc+SBQmDIqeK427pCSw1xVyJooaknlIUlb3TyOaJdI1Wko92rUoYRfTJ/8eZv/GuL8U+kmA8ygu1ByfhFOg69Oyb55OThsgd+p8mMstjE62Rm+sN+8MBUEAllHGYVlKgKaO+HLPFor0fdYxl56CVVsPRWKOmJSXEn8EvuGrstSiiQU6pNZiJoQT3QpR43YhcmigMmTDkUNHgrvinWE0fprY9cLOpbuFJhZ7+OBL34hv/9Ox9QuD4Vb1rJvdeeW5ijVOrOh6JvqaR06JuutDn13q3VU6aJq0pNJwp5ujX84Aa5fQaC7HdcfdJ6ttuYheyoDPlNUyUQuBihg2c3F9tvivSmrvGLd4HV9NUjKZTY7XpYrDsEGcYGNAOO8XHG3PNaHcdM6+/0UclP2obLPVadTOvhEHPOGLRZorFmg7GTBBwafjMMREHTNYt++4JyYm5vUwcfGZX7qT/2YPCplmz1dYDjHmfeCygmYWr6KAP7bHq3wjnrje3BslRMBNu+nY2eaqmSAG5bLsOMUi9qy4+izsNgkVHpRg/uZA3yE+OVfMc5ycj+McrwK2ySrg1zd+/TrNJZTxW/5f9oHWR4kvYPeXcDNlL20fxw9L7CAhLi/Nx0RsC+wwbk+MC20G6vtE7gCsyv3QWyqxPeoJ6KuAoRQ2zCjcKA=
    on_pull_requests: false
    on_success: always
    on_failure: change
